<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ArunMotoori" failures="1" tests="3" name="LoginTest" time="15.395" errors="0" timestamp="2022-06-27T12:14:50 IST">
  <testcase classname="tests.LoginTest" name="loginWithValidCredentials" time="1.183"/>
  <testcase classname="tests.LoginTest" name="loginWithValidUsernameAndInvalidPassword" time="1.028"/>
  <testcase classname="tests.LoginTest" name="loginWithInvalidUsernameAndValidPassword" time="0.985">
    <failure type="java.lang.AssertionError" message="Intentionally failing">
      <![CDATA[java.lang.AssertionError: Intentionally failing
at tests.LoginTest.loginWithInvalidUsernameAndValidPassword(LoginTest.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- loginWithInvalidUsernameAndValidPassword -->
</testsuite> <!-- LoginTest -->
